language: go
go:
  - 1.7.x
  - 1.8.x

script:
  - go test -v ./...
  - go build -o bin/hello -i .

deploy:
  provider: releases
  api_key:
    secure: AOCF1udPK8Lcd1252/2iM/tQ/UyieC4H53WW2MLYmjLg2ARJNbN+lOzU44icUqxJWs53prkE8GENDHZff5bVUA8VoFmIbtcQgCiOu6WaV5zFmj7X2Fq4eS+TeVQRJTiveI4+E/GIHcu/9sGlGfoXLE5OA+YK5myfbXR3L6+DLY3JjlhIXLX/83kIH6qQ2DrlQkFW1qAM/E1AkhxK5cZIC7yqQVZwYxWlhRSqrlctzv0lLMueE5puNHunUtzKbHQs50PeDnymD8CKz0fXlQnuBaZ57K7Q3Kwu2YHqYHCpDB9lZxSxzuSq9n77KVEPQEij/RRteHGcVfl0xa0Ia1Fwxk5BrmsJiyHJ2fiQDNzmuxUhRTYsRus6pzjlcTftjx1GrTYV7x57pe5KvqT3+kj/O2UtThlHC7dQjOMHbWnB+lK/rb4IAg3JcWx5/Js02KkQAHr8bKcCiMb/CcDSOVt/nWV80Z3RzzemPFXJzJOIR5NtPVw9tsQcjebvxN+1supErab3Wx2gQK37faLbo0W1CI0Hz+dJGNX9B/e+ZdytYXIBlNWFVfhYWJ03h7RoEKbjFAbqrFwEFOwE7nlDezqm+xBXK5l3FiwAQ5WqyJcVvbMlUSjWVHNJf3CYycrcs5dJCRcVus3kkvLPhIsHu6B66PS0LI/s+p98SbQpwfXQrV4=
  file: bin/hello
  skip_cleanup: true
  on:
    condition: $TRAVIS_GO_VERSION =~ ^1\.8\.
    tags: true

jobs:
  include:
    - stage: docker
      sudo: required
      dist: trusty
      services:
        - docker
      env:
        - IMAGE_NAME=testblogorganization/hellofaster
        - REGISTRY_USER=testblogdeploy
        - secure: "n1RmZTtrcm5kNeq3IDdQCb7PDAjCMuG5QfGxfsYDkJfhtUPugLFJTzfWyVfBWDyNIFKyyUiPote2neFovJRlefcYf3pO3qiacbC8W0+WVkrGofkT1koDKc9FyoSM5GsPuyUB5Md0DXQ3d4dz48v/Ba2b+wRPy949NL91hLPaK+7R9ghxnl8fW2oIl0pWsfA2stPoRuJ0KY27AgvtrPd+Jrfr0BqcDOSEawaW9fkXWnDh01aXVF/5JOJdqQWDAsdNZbkggOw9TUlO5XE1BIg7WAcxlVgagqbFleHrJhL045fYDFWi+CsAD688KiGZsIHceoOrxZmwh/+wj5Ql0Nuop2FxtW+JmvpdJ8XOxHkfrzNw4F38oJZoMtcKj/KBKIzQMW0c/xCQjxR9eaPsuW1mtPvFPlTN+XZPcLXN9GwQzu9sR3wX3ZOR/oigq/RM2qpL8VIh+ub0ulZOYRFUaPmPlrd3wadQSBUgNrNJTNyc3GzdIrMBGtx9/BwW6kWCI7yTvX2WVPKJ0R5Xi6Rq0TcbEZtXdYuz1hNtsQdlyM2XWDFjQ8BcSxclr4WiHeu0/XyeeTRnQNcHALay86QpmBg44xTGFyjjPacmaf1u36O7xBXDtNY+sY+6MCxJOk836biDknoEUaZi4KhTgL77J79UZV24t7QEm30mqPyL/grhr6Y="

      before_install:
        - sudo apt-get update
        - sudo apt-get install -y -o Dpkg::Options::="--force-confold" docker-engine

      before_script:
        - if [ -n "$TRAVIS_TAG" ]; then cache_from="$IMAGE_NAME"; else cache_from="${IMAGE_NAME}:master"; fi
        - docker pull "$cache_from" || true
      script:
        - docker build --pull --cache-from "$cache_from" -t "$IMAGE_NAME" .

      before_deploy:
        - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
        - if [ -n "$TRAVIS_TAG" ]; then
            tags=("${IMAGE_NAME}:latest" "${IMAGE_NAME}:${TRAVIS_TAG}");
          else
            tags=("${IMAGE_NAME}:master" "${IMAGE_NAME}:$(git rev-parse --short HEAD)-master");
          fi
        - for tag in "${tags[@]}"; do docker tag "$IMAGE_NAME" "$tag"; done
      deploy:
        - provider: script
          script: for tag in "${tags[@]}"; do docker push $tag; done
          on:
            tags: true
        - provider: script
          script: for tag in "${tags[@]}"; do docker push $tag; done
          on:
            branch: master
